### ISSUE TITLE
Notify Testers on each deployment

### ISSUE THREAD

**Issue by roschaefer** [Latias-eu-IT/Discord-Bot#8]
**Is your feature request related to a problem? Please describe.**
We currently have no automated test setup. It will take a while until we have so many software tests that we feel comfortable deploying `develop` to production. Until then, we have to test our `staging` deployment and our `production` deployment manually. This is a tedious task and we don't know when a deployment was successful.

**Describe the solution you'd like**
We have our discord bot sending notification for each deployment of the current alpha version and the version used in staging. Additionally we would like to have a role called `@@Testers` which gets a notification for every deployment. Thus, all testers should know about a deployment and test the current changelog.

**Describe alternatives you've considered**
We could also manually notify testers.

**Additional context**

**Comment by Lulalaby** [comment]
Will be implemented in a few weeks
Prior 1
